In [5]:
# import libraries
import numpy as np
import torch
import torch.nn as nn

In [6]:
# build two models

widenet = nn.Sequential(
    nn.Linear(2,4),  # hidden layer
    nn.Linear(4,3),  # output layer
    )


deepnet = nn.Sequential(
    nn.Linear(2,2),  # hidden layer
    nn.Linear(2,2),  # hidden layer
    nn.Linear(2,3),  # output layer
    )

# print them out to have a look
print(widenet)
print(' ')
print(deepnet)

Sequential(
  (0): Linear(in_features=2, out_features=4, bias=True)
  (1): Linear(in_features=4, out_features=3, bias=True)
)
 
Sequential(
  (0): Linear(in_features=2, out_features=2, bias=True)
  (1): Linear(in_features=2, out_features=2, bias=True)
  (2): Linear(in_features=2, out_features=3, bias=True)
)


# Peeking inside the network

In [7]:
# check out the parameters
for p in deepnet.named_parameters():
  print(p)
  print(' ')

('0.weight', Parameter containing:
tensor([[-0.1814, -0.0373],
        [-0.2126, -0.5551]], requires_grad=True))
 
('0.bias', Parameter containing:
tensor([ 0.2596, -0.3397], requires_grad=True))
 
('1.weight', Parameter containing:
tensor([[-0.1521, -0.0929],
        [-0.1155, -0.0730]], requires_grad=True))
 
('1.bias', Parameter containing:
tensor([0.7023, 0.1249], requires_grad=True))
 
('2.weight', Parameter containing:
tensor([[ 0.0879,  0.1468],
        [-0.3932,  0.4351],
        [-0.1836, -0.4084]], requires_grad=True))
 
('2.bias', Parameter containing:
tensor([ 0.2469, -0.4061,  0.3591], requires_grad=True))
 


In [8]:
# count the number of nodes ( = the number of biases)

# named_parameters() is an iterable that returns the tuple (name,numbers)
numNodesInWide = 0
for p in widenet.named_parameters():
  if 'bias' in p[0]:
    numNodesInWide += len(p[1])

numNodesInDeep = 0
for paramName,paramVect in deepnet.named_parameters():
  if 'bias' in paramName:
    numNodesInDeep += len(paramVect)


print('There are %s nodes in the wide network.' %numNodesInWide)
print('There are %s nodes in the deep network.' %numNodesInDeep)

There are 7 nodes in the wide network.
There are 7 nodes in the deep network.


In [9]:
# just the parameters
for p in widenet.parameters():
  print(p)
  print(' ')

Parameter containing:
tensor([[ 0.5368,  0.1574],
        [-0.0567, -0.0101],
        [-0.5407,  0.5081],
        [ 0.3602, -0.3442]], requires_grad=True)
 
Parameter containing:
tensor([-0.5835, -0.2390, -0.6249,  0.0668], requires_grad=True)
 
Parameter containing:
tensor([[-0.0223, -0.1280,  0.2291,  0.0628],
        [ 0.1287, -0.3929,  0.2866, -0.0035],
        [ 0.0635,  0.1117, -0.0036, -0.1160]], requires_grad=True)
 
Parameter containing:
tensor([-0.0383, -0.2337,  0.3863], requires_grad=True)
 


In [10]:
# now count the total number of trainable parameters
nparams = 0
for p in widenet.parameters():
  if p.requires_grad:
    print('This piece has %s parameters' %p.numel())
    nparams += p.numel()

print('\n\nTotal of %s parameters'%nparams)

This piece has 8 parameters
This piece has 4 parameters
This piece has 12 parameters
This piece has 3 parameters


Total of 27 parameters


In [11]:
# btw, can also use list comprehension

nparams = np.sum([ p.numel() for p in widenet.parameters() if p.requires_grad ])
print('Widenet has %s parameters'%nparams)

nparams = np.sum([ p.numel() for p in deepnet.parameters() if p.requires_grad ])
print('Deepnet has %s parameters'%nparams)


Widenet has 27 parameters
Deepnet has 21 parameters


In [12]:
# A nice simple way to print out the model info.
from torchsummary import summary
summary(widenet,(1,2))


### NOTE ABOUT THE CODE IN THIS CELL:
# torchsummary is being replaced by torchinfo.
# If you are importing these libraries on your own (via pip), then see the following website:
#        https://pypi.org/project/torch-summary/
# However, torchsummary will continue to be supported, so if the code in this cell works (meaning torchsummary is already installed),
# then you don't need to do anything!

----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
            Linear-1                 [-1, 1, 4]              12
            Linear-2                 [-1, 1, 3]              15
Total params: 27
Trainable params: 27
Non-trainable params: 0
----------------------------------------------------------------
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00
----------------------------------------------------------------
